model:
  arch: blip2_opt
  model_type: caption_coco_opt2.7b
  use_grad_checkpoint: False

datasets:
  shutterstock: # name of the dataset builder
    type: "shutterstock_1m"
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        eval:
          name: "blip_caption"

run:
  task: blip2_faiss_construct

  # faiss
  data_root: "../datasets"
  data_name: "shutterstock_1m"
  index_name: "HNSW32,Flat"
  visual_dim: 1408  # vig-g

  # optimizer
  batch_size_train: 512
  batch_size_eval: 512
  num_workers: 16

  max_len: 30
  min_len: 8
  num_beams: 5

  seed: 42
  output_dir: "output/faiss/construct_shutterstock_1m"

  evaluate: True
  test_splits: ["val"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False  # runs on DP, not DDP
