model:
  arch: blip2_opt
  model_type: caption_coco_opt2.7b
  use_grad_checkpoint: False
  load_finetuned: False  # temporary
  fuse_ret_feature: "prefix"  # no matter (cross-attention appending)

datasets:
  nice: # name of the dataset builder
    type: "retaug_default_split_4k"  # datasets.nice.type nice_4k_train_retaug5
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        eval:
          name: "blip_caption"
#     build_info:
#         images:
#             storage: '/export/share/datasets/vision/coco/images/'

run:
  task: nice_captioning
  # optimizer
  batch_size_train: 32
  batch_size_eval: 16
  num_workers: 4

  max_len: 30
  min_len: 8
  num_beams: 5

  seed: 42
  output_dir: "output/BLIP2_eval/opt2.7b_retaug"

  evaluate: True
  test_splits: ["nice_val_split_test"]

  device: "cuda"
  world_size: 4
  dist_url: "env://"
  distributed: True

  memo: ""
