datasets:
  shutterstock:
    type: shutterstock_1m
    data_dir: /home/appuser/datasets/shutterstock/
    data_type: images # [images|videos|features]

    build_info:
      annotations:
        val:
          url: /home/appuser/datasets/shutterstock/shutterstock_1m.json
          storage:  /home/appuser/datasets/shutterstock/shutterstock_1m.json
      images:
        storage: /home/appuser/datasets/shutterstock/