datasets:
  nice:
    data_dir: /home/appuser/datasets/nice/
    data_type: images

    build_info:
      annotations:
        discovery_nice_test_top1:
          url: /home/appuser/datasets/nice/discovery_nice_test_top1.json
          storage:  /home/appuser/datasets/nice/discovery_nice_test_top1.json
      images:
        storage: /home/appuser/datasets/nice/
