datasets:
  nice:
    data_dir: /home/appuser/datasets/nice/
    data_type: images # [images|videos|features]
    max_ret: 3

    build_info:
      annotations:
        train:
          url: /home/appuser/datasets/nice/discovery_nice_test_top1_ret_ids.json
          storage: /home/appuser/datasets/nice/discovery_nice_test_top1_ret_ids.json
          ret_features: /home/appuser/datasets/shutterstock/caption_features/text_feature_nice_discovery_top1.h5
        nice_val_split_test:
          url: /home/appuser/datasets/nice/nice_val_split_test_ret_ids.json
          storage:  /home/appuser/datasets/nice/nice_val_split_test_ret_ids.json
          ret_features: /home/appuser/datasets/shutterstock/caption_features/text_feature_nice_val.h5
      images:
        storage: /home/appuser/datasets/nice/
