model:
  arch: blip2_opt
  model_type: caption_coco_opt2.7b
  use_grad_checkpoint: False

  # retrieval-augmented fusion options
  fuse_ret_feature: "visual_patch"  # ["query_output", "visual_patch"]
  ret_k: 2  # number of top-k retrived feature points to be aggregagated (averaged)

datasets:
  nice:
    type: "eval_with_retrieval"
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        eval:
          name: "blip_caption"

run:
  task: nice_captioning
  # optimizer
  batch_size_train: 16
  batch_size_eval: 16
  num_workers: 4

  max_len: 30
  min_len: 8
  num_beams: 5

  seed: 42
  output_dir: "output/BLIP2/eval/blip2_opt2.7b_fusion_visual_patch_k_2"

  evaluate: True
  test_splits: ["test"]  # ["nice_val", "test", "nice_val_split_test"]

  device: "cuda"
  world_size: 4
  dist_url: "env://"
  distributed: True

  memo: ""
  load_checkpoint: "PATH_TO_CKPT"
