model:
  arch: blip2_opt
  model_type: caption_coco_opt2.7b
  load_finetuned: False
  use_grad_checkpoint: True
  freeze_vit: False
  
  # retrieval-augmented options
  fuse_ret_feature: "visual_patch"  # ["query_output", "visual_patch"]
  ret_k: 2  # number of top-k retrived feature points to be aggregagated

datasets:
  nice:
    type: "train_split_4k_with_fusion"
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 364
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        train:
          name: "blip_caption"
          prompt: "a photo of "
        eval:
          name: "blip_caption"
run:
  task: nice_captioning
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 4e-5
  min_lr: 0
  warmup_lr: 1e-8
  warmup_steps: 100
  weight_decay: 0.05
  max_epoch: 20
  batch_size_train: 16
  batch_size_eval: 8
  num_workers: 4
  accum_grad_iters: 1

  max_to_keep: 1  # ckpt options

  log_freq: 20

  max_len: 30
  min_len: 8
  num_beams: 5

  seed: 42
  output_dir: "output/BLIP2/vit_g_opt2.7b/nice_split_valid4k_supervised/ret_fusion_visual_patch_emb_avg_top2"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["nice_val_split_test"]
  test_splits: []

  device: "cuda"
  world_size: 4
  dist_url: "env://"
  distributed: True

  memo: ""
